# -*- coding: utf-8 -*-
"""Requirment.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1aYUzMbUVlf0u2CtTre7RVB9G_juUNxL4
"""

streamlit
Scikit-learn
pandas
numpy
pickle
